#!/usr/bin/perl

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/lib";

use App::Rad;
use PagSeguro::API;

# show transactions
sub transaction
:Help(qq{
    \ttransaction by code:\n\t--email=you\@email.com --code=[transaction_code] --token=[account_token]\n
    \ttransaction by date range:\n\t--email=you\@email.com --initial='2013-10-01T00:00' --final='2013-10-01T00:00' --token=[account_token]
}){
    my $c = shift;

    # api instance
    my $ps = PagSeguro::API->new(
        email => $c->options->{email}, token => $c->options->{token}
    );

    # transaction by code
    if($c->options->{code}){
        my $code = $c->options->{code} || undef;
        
        my $res;
        eval{
            use Data::Dumper;
            $res = Dumper $ps->transaction->load($code);
        };
        if($@){
            print "Error: $@\n";
            exit;
        }
    
        print $res and exit;
    }

    # transaction by date range
    if($c->options->{initial} && $c->options->{final}){
        my $initial = $c->options->{initial} || undef;
        my $final = $c->options->{final} || undef;
        
        my $res;
        eval{
            use Data::Dumper;
            $res = Dumper $ps->transaction->search(
                initial => $initial, final => $final
            );
        };
        if($@){
            print "Error: $@\n";
            exit;
        }
    
        print $res and exit;
    }
}

# app run
App::Rad->run;
